server:
  port: 8090
  servlet:
    context-path: /api

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://localhost:8123/api
          predicates:
            - Path=/api/name/**
        - id: model_route
          uri: http://localhost:8000/task
          predicates:
            - Path=/api/task/**
        - id: BI_route
          uri: http://localhost:8125/api/chart
          predicates:
            - Path=/api/chart/**

        - id: QA_route
          uri: http://localhost:8001/api/qasystem
          predicates:
            - Path=/api/qasystem/**



dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848