server:
  port: 8090
  servlet:
    context-path: /api

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: model_route
          uri: http://101.43.233.52:8000/api/task/model
          predicates:
            - Path=/api/task/**
        - id: BI_route
          uri: http://101.43.233.52:8125/api/chart/generateByAPI
          predicates:
            - Path=/api/chart/**

        - id: chat_route
          uri: http://101.201.81.126:8000/api/qasystem/getRes
          predicates:
            - Path=/api/qasystem/**


        - id: Qwen_route
          uri: http://101.43.233.52:8000
          predicates:
            - Path=/api/chat/**
          filters:
            - RewritePath=/api/chat/(?<segment>.*), /api/task/$\{segment}






dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://101.201.81.126:8848